<a href="https://colab.research.google.com/github/thanhlamnguyen/AeThongMinh/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Khai báo thư viện Numpy

In [ ]:
import numpy as np

2. Khởi tạo vecto/ma trận

In [7]:
x = [[1,2,3], [4,5,6]]
print ('a =',np.array(x))

a = [[1 2 3]
 [4 5 6]]


3. Tỉnh tổng, trừ, tích 2 ma trận

In [8]:
import numpy as np
x = [((1,2),(3,4)), ((4,5),(6,7))]
y = [((6,7),(8,9)), ((9,10),(11,12))]
a = np.array(x)
b = np.array(y)
print ('a+b =',a + b)
print ('a-b =',a - b)
print ('a*b =',a.dot(b))

a+b = [[[ 7  9]
  [11 13]]

 [[13 15]
  [17 19]]]
a-b = [[[-5 -5]
  [-5 -5]]

 [[-5 -5]
  [-5 -5]]]
a*b = [[[[ 22  25]
   [ 31  34]]

  [[ 50  57]
   [ 71  78]]]


 [[[ 64  73]
   [ 91 100]]

  [[ 92 105]
   [131 144]]]]


4. Tính chuyển vị

In [9]:
x = [[1,2,3], [4,5,6]]
y = np.transpose(x)
print ('ma trận của x',x)
print ('ma trận chuyển vị của x',y)

ma trận của x [[1, 2, 3], [4, 5, 6]]
ma trận chuyển vị của x [[1 4]
 [2 5]
 [3 6]]
